repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v1.12.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        python_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.1.1
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
      - id: mypy
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
